/*
 * Napisane 12.2018 pierwsze kroki pisanie w JAVA. 
 */
package pasekmenu;

/**
 *
 * @author DELL
 */
public class NewJFrame extends javax.swing.JFrame {

   /**
    * Creates new form NewJFrame
    */
   public NewJFrame() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jMenuBar2 = new javax.swing.JMenuBar();
      jMenu5 = new javax.swing.JMenu();
      jMenu6 = new javax.swing.JMenu();
      buttonGroup1 = new javax.swing.ButtonGroup();
      jMenuBar1 = new javax.swing.JMenuBar();
      jMenu1 = new javax.swing.JMenu();
      Zapis = new javax.swing.JMenuItem();
      jMenuItem2 = new javax.swing.JMenuItem();
      jSeparator1 = new javax.swing.JPopupMenu.Separator();
      jMenu4 = new javax.swing.JMenu();
      jMenuItem3 = new javax.swing.JMenuItem();
      jMenuItem4 = new javax.swing.JMenuItem();
      jMenuItem5 = new javax.swing.JMenuItem();
      tylkoOczyt = new javax.swing.JCheckBoxMenuItem();
      jMenu2 = new javax.swing.JMenu();
      jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
      jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
      jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
      jMenu3 = new javax.swing.JMenu();
      jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
      jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
      jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
      jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();

      jMenu5.setText("File");
      jMenuBar2.add(jMenu5);

      jMenu6.setText("Edit");
      jMenuBar2.add(jMenu6);

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jMenu1.setText("File");
      jMenu1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenu1ActionPerformed(evt);
         }
      });

      Zapis.setText("Zapisz");
      Zapis.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            ZapisActionPerformed(evt);
         }
      });
      jMenu1.add(Zapis);

      jMenuItem2.setText("Wczytaj");
      jMenu1.add(jMenuItem2);
      jMenu1.add(jSeparator1);

      jMenu4.setText("Opcje");

      jMenuItem3.setText("Opcja 1");
      jMenu4.add(jMenuItem3);

      jMenuItem4.setText("Opcja 2");
      jMenu4.add(jMenuItem4);

      jMenuItem5.setText("Opcja 3");
      jMenu4.add(jMenuItem5);

      tylkoOczyt.setText("Tylko odczyt");
      tylkoOczyt.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            tylkoOczytActionPerformed(evt);
         }
      });
      jMenu4.add(tylkoOczyt);

      jMenu1.add(jMenu4);

      jMenuBar1.add(jMenu1);

      jMenu2.setText("Edit");

      buttonGroup1.add(jRadioButtonMenuItem1);
      jRadioButtonMenuItem1.setSelected(true);
      jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");
      jMenu2.add(jRadioButtonMenuItem1);

      buttonGroup1.add(jRadioButtonMenuItem2);
      jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");
      jMenu2.add(jRadioButtonMenuItem2);

      buttonGroup1.add(jRadioButtonMenuItem3);
      jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");
      jMenu2.add(jRadioButtonMenuItem3);

      jMenuBar1.add(jMenu2);

      jMenu3.setText("Help");

      jCheckBoxMenuItem1.setSelected(true);
      jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");
      jMenu3.add(jCheckBoxMenuItem1);

      jCheckBoxMenuItem2.setSelected(true);
      jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");
      jMenu3.add(jCheckBoxMenuItem2);

      jCheckBoxMenuItem3.setSelected(true);
      jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");
      jMenu3.add(jCheckBoxMenuItem3);

      jCheckBoxMenuItem4.setSelected(true);
      jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");
      jMenu3.add(jCheckBoxMenuItem4);

      jMenuBar1.add(jMenu3);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 400, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 277, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void ZapisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZapisActionPerformed
      System.out.println("Zapisuję pracę!!!");
   }//GEN-LAST:event_ZapisActionPerformed

   private void tylkoOczytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tylkoOczytActionPerformed
      if (tylkoOczyt.isSelected()) Zapis.setEnabled(false);
      else Zapis.setEnabled(true);
   }//GEN-LAST:event_tylkoOczytActionPerformed

   private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

   }//GEN-LAST:event_jMenu1ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
        //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new NewJFrame().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JMenuItem Zapis;
   private javax.swing.ButtonGroup buttonGroup1;
   private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
   private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
   private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
   private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenu jMenu2;
   private javax.swing.JMenu jMenu3;
   private javax.swing.JMenu jMenu4;
   private javax.swing.JMenu jMenu5;
   private javax.swing.JMenu jMenu6;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JMenuBar jMenuBar2;
   private javax.swing.JMenuItem jMenuItem2;
   private javax.swing.JMenuItem jMenuItem3;
   private javax.swing.JMenuItem jMenuItem4;
   private javax.swing.JMenuItem jMenuItem5;
   private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
   private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
   private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
   private javax.swing.JPopupMenu.Separator jSeparator1;
   private javax.swing.JCheckBoxMenuItem tylkoOczyt;
   // End of variables declaration//GEN-END:variables
}
