
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/*
 * Napisane 12.2018 pierwsze kroki pisanie w JAVA. 
 */

/**
 *
 * @author DELL
 */
public class PrzelaczRadio extends javax.swing.JFrame {

   /**
    * Creates new form PrzelaczRadio
    */
   public PrzelaczRadio() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      grupaRadioRozmiar = new javax.swing.ButtonGroup();
      grupaRadioKolor = new javax.swing.ButtonGroup();
      malyPrzelacznikRadioRozmiar = new javax.swing.JRadioButton();
      sredniPrzelacznikRadioRozmiar = new javax.swing.JRadioButton();
      duzyPrzelacznikRadioRozmiar = new javax.swing.JRadioButton();
      czerwonyPrzelacznikRadioKolor = new javax.swing.JRadioButton();
      niebieskiPrzelacznikRadioKolor = new javax.swing.JRadioButton();
      zielonyPrzelacznikRadioKolor = new javax.swing.JRadioButton();
      tekstZmianaLabel = new javax.swing.JLabel();
      pogrubionyCheck = new javax.swing.JCheckBox();
      pochylonyCheck = new javax.swing.JCheckBox();
      jTextField1 = new javax.swing.JTextField();
      jComboBox1 = new javax.swing.JComboBox();

      grupaRadioRozmiar.add(malyPrzelacznikRadioRozmiar);
      grupaRadioRozmiar.add(sredniPrzelacznikRadioRozmiar);
      grupaRadioRozmiar.add(duzyPrzelacznikRadioRozmiar);

      grupaRadioKolor.add(czerwonyPrzelacznikRadioKolor);
      grupaRadioKolor.add(niebieskiPrzelacznikRadioKolor);
      grupaRadioKolor.add(zielonyPrzelacznikRadioKolor);

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setPreferredSize(new java.awt.Dimension(1000, 360));

      malyPrzelacznikRadioRozmiar.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
      malyPrzelacznikRadioRozmiar.setText("Mały");
      malyPrzelacznikRadioRozmiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      malyPrzelacznikRadioRozmiar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            malyPrzelacznikRadioRozmiarActionPerformed(evt);
         }
      });

      sredniPrzelacznikRadioRozmiar.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
      sredniPrzelacznikRadioRozmiar.setText("Średni");
      sredniPrzelacznikRadioRozmiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      sredniPrzelacznikRadioRozmiar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            sredniPrzelacznikRadioRozmiarActionPerformed(evt);
         }
      });

      duzyPrzelacznikRadioRozmiar.setFont(new java.awt.Font("Dialog", 1, 35)); // NOI18N
      duzyPrzelacznikRadioRozmiar.setText("Duży");
      duzyPrzelacznikRadioRozmiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      duzyPrzelacznikRadioRozmiar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            duzyPrzelacznikRadioRozmiarActionPerformed(evt);
         }
      });

      czerwonyPrzelacznikRadioKolor.setBackground(new java.awt.Color(255, 0, 51));
      czerwonyPrzelacznikRadioKolor.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
      czerwonyPrzelacznikRadioKolor.setForeground(new java.awt.Color(255, 0, 51));
      czerwonyPrzelacznikRadioKolor.setText("Czerwony");
      czerwonyPrzelacznikRadioKolor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      czerwonyPrzelacznikRadioKolor.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            czerwonyPrzelacznikRadioKolorActionPerformed(evt);
         }
      });

      niebieskiPrzelacznikRadioKolor.setBackground(new java.awt.Color(0, 0, 255));
      niebieskiPrzelacznikRadioKolor.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
      niebieskiPrzelacznikRadioKolor.setForeground(new java.awt.Color(0, 0, 204));
      niebieskiPrzelacznikRadioKolor.setText("Niebieski");
      niebieskiPrzelacznikRadioKolor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      niebieskiPrzelacznikRadioKolor.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            niebieskiPrzelacznikRadioKolorActionPerformed(evt);
         }
      });

      zielonyPrzelacznikRadioKolor.setBackground(new java.awt.Color(0, 204, 0));
      zielonyPrzelacznikRadioKolor.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
      zielonyPrzelacznikRadioKolor.setForeground(new java.awt.Color(0, 204, 0));
      zielonyPrzelacznikRadioKolor.setText("Zielony");
      zielonyPrzelacznikRadioKolor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      zielonyPrzelacznikRadioKolor.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            zielonyPrzelacznikRadioKolorActionPerformed(evt);
         }
      });

      tekstZmianaLabel.setBackground(new java.awt.Color(204, 0, 204));
      tekstZmianaLabel.setFont(new java.awt.Font("DejaVu Serif", 1, 15)); // NOI18N
      tekstZmianaLabel.setForeground(new java.awt.Color(255, 255, 255));
      tekstZmianaLabel.setText("To jest tekst, który będzie zmieniany.");
      tekstZmianaLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
      tekstZmianaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseEntered(java.awt.event.MouseEvent evt) {
            tekstZmianaLabelMouseEntered(evt);
         }
      });
      tekstZmianaLabel.setFont(new java.awt.Font("DejaVu Serif", 0, 25));

      pogrubionyCheck.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      pogrubionyCheck.setText("POGRUBIONY");
      pogrubionyCheck.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            pogrubionyCheckActionPerformed(evt);
         }
      });

      pochylonyCheck.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      pochylonyCheck.setText("POCHYLONY");
      pochylonyCheck.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            pochylonyCheckActionPerformed(evt);
         }
      });

      jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            jTextField1KeyPressed(evt);
         }
         public void keyTyped(java.awt.event.KeyEvent evt) {
            jTextField1KeyTyped(evt);
         }
      });

      jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Metal", "Motif", "Windows" }));
      jComboBox1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox1ActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(51, 51, 51)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(tekstZmianaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(czerwonyPrzelacznikRadioKolor)
                     .addComponent(niebieskiPrzelacznikRadioKolor)
                     .addComponent(zielonyPrzelacznikRadioKolor))
                  .addGap(83, 83, 83)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(sredniPrzelacznikRadioRozmiar)
                     .addComponent(malyPrzelacznikRadioRozmiar)
                     .addComponent(duzyPrzelacznikRadioRozmiar))
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(pogrubionyCheck)
                           .addComponent(pochylonyCheck))
                        .addGap(540, 540, 540))
                     .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jComboBox1, 0, 154, Short.MAX_VALUE)
                           .addComponent(jTextField1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
      );

      layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {duzyPrzelacznikRadioRozmiar, malyPrzelacznikRadioRozmiar, sredniPrzelacznikRadioRozmiar});

      layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {czerwonyPrzelacznikRadioKolor, niebieskiPrzelacznikRadioKolor, zielonyPrzelacznikRadioKolor});

      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(tekstZmianaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(czerwonyPrzelacznikRadioKolor)
               .addComponent(malyPrzelacznikRadioRozmiar)
               .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(niebieskiPrzelacznikRadioKolor)
                  .addComponent(sredniPrzelacznikRadioRozmiar))
               .addGroup(layout.createSequentialGroup()
                  .addGap(4, 4, 4)
                  .addComponent(pogrubionyCheck)
                  .addGap(18, 18, 18)
                  .addComponent(pochylonyCheck)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(zielonyPrzelacznikRadioKolor)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(duzyPrzelacznikRadioRozmiar)
                  .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(76, Short.MAX_VALUE))
      );

      layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {duzyPrzelacznikRadioRozmiar, malyPrzelacznikRadioRozmiar, sredniPrzelacznikRadioRozmiar});

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void malyPrzelacznikRadioRozmiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malyPrzelacznikRadioRozmiarActionPerformed
      tekstZmianaLabel.setFont(new Font("Monospaced",1,15));
   }//GEN-LAST:event_malyPrzelacznikRadioRozmiarActionPerformed

   private void sredniPrzelacznikRadioRozmiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sredniPrzelacznikRadioRozmiarActionPerformed
      tekstZmianaLabel.setFont(new Font("Monospaced",1,25));
   }//GEN-LAST:event_sredniPrzelacznikRadioRozmiarActionPerformed

   private void duzyPrzelacznikRadioRozmiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duzyPrzelacznikRadioRozmiarActionPerformed
      tekstZmianaLabel.setFont(new Font("Monospaced",1,35));
   }//GEN-LAST:event_duzyPrzelacznikRadioRozmiarActionPerformed

   private void czerwonyPrzelacznikRadioKolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_czerwonyPrzelacznikRadioKolorActionPerformed
      tekstZmianaLabel.setForeground(Color.RED);
   }//GEN-LAST:event_czerwonyPrzelacznikRadioKolorActionPerformed

   private void niebieskiPrzelacznikRadioKolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niebieskiPrzelacznikRadioKolorActionPerformed
    tekstZmianaLabel.setForeground(Color.BLUE);
   }//GEN-LAST:event_niebieskiPrzelacznikRadioKolorActionPerformed

   private void zielonyPrzelacznikRadioKolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zielonyPrzelacznikRadioKolorActionPerformed
     tekstZmianaLabel.setForeground(Color.GREEN);
   }//GEN-LAST:event_zielonyPrzelacznikRadioKolorActionPerformed

   private void tekstZmianaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tekstZmianaLabelMouseEntered
     tekstZmianaLabel.setForeground(Color.BLACK);
   }//GEN-LAST:event_tekstZmianaLabelMouseEntered

   private void pogrubionyCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pogrubionyCheckActionPerformed
         zmienStyle();
//      if ((tekstZmianaLabel.isDisplayable())&(tekstZmianaLabel.getFont().getStyle()!=Font.BOLD ))
//      tekstZmianaLabel.setFont(new Font(tekstZmianaLabel.getFont().getFamily(), tekstZmianaLabel.getFont().getStyle()+Font.BOLD, tekstZmianaLabel.getFont().getSize()));
   }//GEN-LAST:event_pogrubionyCheckActionPerformed

   private void pochylonyCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pochylonyCheckActionPerformed
         zmienStyle();
   }//GEN-LAST:event_pochylonyCheckActionPerformed

   private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
     if (!jestLiczba(evt.getKeyChar())) 
        evt.consume();
   }//GEN-LAST:event_jTextField1KeyTyped

   private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
      if (evt.isControlDown() && evt.getKeyCode()==KeyEvent.VK_V)
      {
         Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
         DataFlavor flavor = DataFlavor.stringFlavor;
         String schowek = "";
         
         try {
            schowek = (String)clipboard.getData(flavor);
         } catch (UnsupportedFlavorException ex) {
            Logger.getLogger(PrzelaczRadio.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
            Logger.getLogger(PrzelaczRadio.class.getName()).log(Level.SEVERE, null, ex);
         }
         for (int i = 0; i < schowek.length(); i++)
            if (!jestLiczba(schowek.charAt(i)))
            {
               evt.consume();
               break;
            }
      }
   }//GEN-LAST:event_jTextField1KeyPressed

   private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
     
      String nazwaWygladu = "";
      
      if (((JComboBox)evt.getSource()).getSelectedItem().equals("Metal"))
         nazwaWygladu = "javax.swing.plaf.metal.MetalLookAndFeel";
      if (((JComboBox)evt.getSource()).getSelectedItem().equals("Windows"))
         nazwaWygladu = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
      if (((JComboBox)evt.getSource()).getSelectedItem().equals("Motif"))
         nazwaWygladu = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";   
      
      
     try
     {
     UIManager.setLookAndFeel(nazwaWygladu);
     SwingUtilities.updateComponentTreeUI(this);
     }
     catch(Exception ex)
             {
                System.out.println(ex.getMessage());
             }
   }//GEN-LAST:event_jComboBox1ActionPerformed
private boolean jestLiczba(char zn)
{
   if (zn>='0' && zn<='9')
      return true;
   
   return false;
}
   private void zmienStyle() 
   {
      int style = Font.PLAIN;
      if (pogrubionyCheck.isSelected()) style += Font.BOLD;
      if (pochylonyCheck.isSelected()) style += Font.ITALIC;
      tekstZmianaLabel.setFont(new Font(tekstZmianaLabel.getFont().getFamily(), style, tekstZmianaLabel.getFont().getSize()));
   }

   
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(PrzelaczRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(PrzelaczRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(PrzelaczRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(PrzelaczRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
        //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new PrzelaczRadio().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JRadioButton czerwonyPrzelacznikRadioKolor;
   private javax.swing.JRadioButton duzyPrzelacznikRadioRozmiar;
   private javax.swing.ButtonGroup grupaRadioKolor;
   private javax.swing.ButtonGroup grupaRadioRozmiar;
   private javax.swing.JComboBox jComboBox1;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JRadioButton malyPrzelacznikRadioRozmiar;
   private javax.swing.JRadioButton niebieskiPrzelacznikRadioKolor;
   private javax.swing.JCheckBox pochylonyCheck;
   private javax.swing.JCheckBox pogrubionyCheck;
   private javax.swing.JRadioButton sredniPrzelacznikRadioRozmiar;
   private javax.swing.JLabel tekstZmianaLabel;
   private javax.swing.JRadioButton zielonyPrzelacznikRadioKolor;
   // End of variables declaration//GEN-END:variables
}
